# Generated by Django 4.2.14 on 2024-08-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='message',
        ),
        migrations.AddField(
            model_name='query',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='family',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='history',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='lifestyle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='other',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='symptoms',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='tests',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
